# Generated by Django 3.2.9 on 2022-04-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tarea_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='valor_acordado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
