# Generated by Django 4.0.1 on 2022-04-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tarea_valor_acordado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_Tarea',
            new_name='fecha_tarea',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='cacelado',
            field=models.BooleanField(default=False),
        ),
    ]
