# Generated by Django 4.0.1 on 2022-04-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_fecha_tarea_tarea_fecha_tarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('TAR', 'Tarea'), ('REC', 'Recuperacion'), ('PRU', 'Prueba'), ('SUP', 'Examen Sup.'), ('PRO', 'Proyecto')], default=('TAR', 'Tarea'), max_length=3),
        ),
    ]
