# Generated by Django 4.0.1 on 2022-04-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tarea_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='notas_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('TAR', 'Tarea'), ('REC', 'Recuperacion'), ('PRU', 'Prueba'), ('SUP', 'Examen Sup.'), ('PRO', 'Proyecto')], default='TAR', max_length=3),
        ),
    ]
