# Generated by Django 4.0.1 on 2022-04-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tarea_nombre_alter_tarea_notas_adicionales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='cacelado',
            new_name='cancelado',
        ),
    ]
